security:
    encoders:
        AppBundle\Entity\LoginUser:
            algorithm: bcrypt
            cost: 13

    providers:
        db_provider:
            entity:
                class: AppBundle:LoginUser
                property: username

    firewalls:
        main:
            pattern: ^/
            http_basic: ~
            provider: db_provider
