services:
    app.login_user:
        class: AppBundle\Service\LoginUserService
        arguments:
            em: "@doctrine.orm.entity_manager"
            pe: "@security.password_encoder"

    app.print_model:
        class: AppBundle\Service\PrintModelService
        arguments:
            em: "@doctrine.orm.entity_manager"
            c: "@service_container"
